version: 0.2
phases:
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - REPOSITORY_URI=417732881703.dkr.ecr.eu-west-1.amazonaws.com/windows-container-project
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    - docker build -t $REPOSITORY_URI:latest src/sample-app
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build: 
    commands:
    - docker images
    - echo Build completed on `date` 
    - echo pushing to repo
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG